#!/usr/bin/env python3
"""Upload all 31 instruments to Supabase from supabase-instruments-data.md.

Usage:
    .venv/bin/python scripts/upload_instruments.py
"""

import os

from dotenv import load_dotenv

from supabase import create_client

load_dotenv()

STORAGE_BASE = "https://lmxvjdyhwgellfeqybei.supabase.co/storage/v1/object/public/instrument-images"

INSTRUMENTS = [
    # --- Indices ---
    {
        "symbol": "NQ",
        "name": "Nasdaq 100 E-mini",
        "exchange": "CME",
        "category": "index",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro", "options"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["09:30", "16:15"]},
            "tick_size": 0.25,
            "tick_value": 5.0,
            "point_value": 20,
        },
    },
    {
        "symbol": "ES",
        "name": "E-mini S&P 500",
        "exchange": "CME",
        "category": "index",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro", "options"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["09:30", "16:15"]},
            "tick_size": 0.25,
            "tick_value": 12.50,
            "point_value": 50,
        },
    },
    {
        "symbol": "YM",
        "name": "E-mini Dow Jones",
        "exchange": "CBOT",
        "category": "index",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro", "options"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["09:30", "16:15"]},
            "tick_size": 1,
            "tick_value": 5,
            "point_value": 5,
        },
    },
    {
        "symbol": "RTY",
        "name": "E-mini Russell 2000",
        "exchange": "CME",
        "category": "index",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro", "options"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["09:30", "16:15"]},
            "tick_size": 0.1,
            "tick_value": 5,
            "point_value": 50,
        },
    },
    {
        "symbol": "FDAX",
        "name": "DAX Index Futures",
        "exchange": "EUREX",
        "category": "index",
        "currency": "EUR",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["19:15", "16:00"], "RTH": ["03:00", "11:30"]},
            "tick_size": 1,
            "tick_value": 25,
            "point_value": 25,
        },
    },
    {
        "symbol": "FESX",
        "name": "Euro Stoxx 50 Index Futures",
        "exchange": "EUREX",
        "category": "index",
        "currency": "EUR",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["19:15", "16:00"], "RTH": ["03:00", "11:30"]},
            "tick_size": 1,
            "tick_value": 10,
            "point_value": 10,
        },
    },
    # --- Energy ---
    {
        "symbol": "CL",
        "name": "WTI Crude Oil Futures",
        "exchange": "NYMEX",
        "category": "energy",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro", "oil"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["09:00", "14:30"]},
            "tick_size": 0.01,
            "tick_value": 10.0,
            "point_value": 1000,
        },
    },
    {
        "symbol": "BRN",
        "name": "Brent Crude Oil Futures",
        "exchange": "ICEEUR",
        "category": "energy",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro", "oil"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": "Unadjusted continuous contract (actual historic traded prices, no adjustments). Rollover date may differ from other platforms, causing a constant OHLC offset. Indicators are correct.",
        "config": {
            "sessions": {"ETH": ["20:00", "17:00"], "RTH": ["03:00", "14:30"]},
            "tick_size": 0.01,
            "tick_value": 10.0,
            "point_value": 1000,
        },
    },
    {
        "symbol": "NG",
        "name": "Henry Hub Natural Gas Futures",
        "exchange": "NYMEX",
        "category": "energy",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro", "oil"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["09:00", "14:30"]},
            "tick_size": 0.001,
            "tick_value": 10.0,
            "point_value": 10000,
        },
    },
    {
        "symbol": "RB",
        "name": "RBOB Gasoline Futures",
        "exchange": "NYMEX",
        "category": "energy",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro", "oil"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["09:00", "14:30"]},
            "tick_size": 0.0001,
            "tick_value": 4.20,
            "point_value": 42000,
        },
    },
    {
        "symbol": "HO",
        "name": "NY Harbor ULSD Futures",
        "exchange": "NYMEX",
        "category": "energy",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro", "oil"],
        "data_start": "2008-02-15",
        "data_end": "2026-02-06",
        "notes": "Unadjusted continuous contract (actual historic traded prices, no adjustments). Rollover date may differ from other platforms, causing a constant OHLC offset. Indicators are correct.",
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["09:00", "14:30"]},
            "tick_size": 0.0001,
            "tick_value": 4.20,
            "point_value": 42000,
        },
    },
    # --- Metals ---
    {
        "symbol": "GC",
        "name": "Gold Futures",
        "exchange": "COMEX",
        "category": "metals",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["08:20", "13:30"]},
            "tick_size": 0.1,
            "tick_value": 10.0,
            "point_value": 100,
        },
    },
    {
        "symbol": "SI",
        "name": "Silver Futures",
        "exchange": "COMEX",
        "category": "metals",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["08:20", "13:30"]},
            "tick_size": 0.005,
            "tick_value": 25.0,
            "point_value": 5000,
        },
    },
    {
        "symbol": "HG",
        "name": "Copper Futures",
        "exchange": "COMEX",
        "category": "metals",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["08:20", "13:30"]},
            "tick_size": 0.0005,
            "tick_value": 12.50,
            "point_value": 25000,
        },
    },
    {
        "symbol": "PL",
        "name": "Platinum Futures",
        "exchange": "NYMEX",
        "category": "metals",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": "Unadjusted continuous contract (actual historic traded prices, no adjustments). Rollover date may differ from other platforms, causing a constant OHLC offset. Indicators are correct.",
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["08:20", "13:30"]},
            "tick_size": 0.1,
            "tick_value": 5,
            "point_value": 50,
        },
    },
    # --- Currencies ---
    {
        "symbol": "6A",
        "name": "Australian Dollar Futures",
        "exchange": "CME",
        "category": "currency",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["08:20", "16:00"]},
            "tick_size": 0.00005,
            "tick_value": 5.0,
            "point_value": 100000,
        },
    },
    {
        "symbol": "6B",
        "name": "British Pound Futures",
        "exchange": "CME",
        "category": "currency",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["08:20", "16:00"]},
            "tick_size": 0.0001,
            "tick_value": 6.25,
            "point_value": 62500,
        },
    },
    {
        "symbol": "6C",
        "name": "Canadian Dollar Futures",
        "exchange": "CME",
        "category": "currency",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["08:20", "16:00"]},
            "tick_size": 0.00005,
            "tick_value": 5.0,
            "point_value": 100000,
        },
    },
    {
        "symbol": "6E",
        "name": "Euro FX Futures",
        "exchange": "CME",
        "category": "currency",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["08:20", "16:00"]},
            "tick_size": 0.00005,
            "tick_value": 6.25,
            "point_value": 125000,
        },
    },
    {
        "symbol": "6J",
        "name": "Japanese Yen Futures",
        "exchange": "CME",
        "category": "currency",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["08:20", "16:00"]},
            "tick_size": 0.0000005,
            "tick_value": 6.25,
            "point_value": 12500000,
        },
    },
    {
        "symbol": "6S",
        "name": "Swiss Franc Futures",
        "exchange": "CME",
        "category": "currency",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["08:20", "16:00"]},
            "tick_size": 0.00005,
            "tick_value": 6.25,
            "point_value": 125000,
        },
    },
    # --- Treasuries ---
    {
        "symbol": "ZN",
        "name": "10-Year T-Note Futures",
        "exchange": "CBOT",
        "category": "treasury",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["08:20", "15:00"]},
            "tick_size": 0.015625,
            "tick_value": 15.625,
            "point_value": 1000,
        },
    },
    {
        "symbol": "ZF",
        "name": "5-Year T-Note Futures",
        "exchange": "CBOT",
        "category": "treasury",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["08:20", "15:00"]},
            "tick_size": 0.0078125,
            "tick_value": 7.8125,
            "point_value": 1000,
        },
    },
    {
        "symbol": "ZT",
        "name": "2-Year T-Note Futures",
        "exchange": "CBOT",
        "category": "treasury",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["08:20", "15:00"]},
            "tick_size": 0.00390625,
            "tick_value": 7.8125,
            "point_value": 2000,
        },
    },
    {
        "symbol": "US",
        "name": "30-Year T-Bond Futures",
        "exchange": "CBOT",
        "category": "treasury",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["08:20", "15:00"]},
            "tick_size": 0.03125,
            "tick_value": 31.25,
            "point_value": 1000,
        },
    },
    # --- Agriculture ---
    {
        "symbol": "ZC",
        "name": "Corn Futures",
        "exchange": "CBOT",
        "category": "agriculture",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-02-19",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["20:00", "14:20"], "RTH": ["09:30", "14:20"]},
            "tick_size": 0.25,
            "tick_value": 12.50,
            "point_value": 50,
        },
    },
    {
        "symbol": "ZW",
        "name": "Wheat Futures",
        "exchange": "CBOT",
        "category": "agriculture",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["20:00", "14:20"], "RTH": ["09:30", "14:20"]},
            "tick_size": 0.25,
            "tick_value": 12.50,
            "point_value": 50,
        },
    },
    {
        "symbol": "ZS",
        "name": "Soybean Futures",
        "exchange": "CBOT",
        "category": "agriculture",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-03-03",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["20:00", "14:20"], "RTH": ["09:30", "14:20"]},
            "tick_size": 0.25,
            "tick_value": 12.50,
            "point_value": 50,
        },
    },
    {
        "symbol": "KC",
        "name": "Coffee C Futures",
        "exchange": "ICEUS",
        "category": "agriculture",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": "Unadjusted continuous contract (actual historic traded prices, no adjustments). Rollover date may differ from other platforms, causing a constant OHLC offset. Indicators are correct.",
        "config": {
            "sessions": {"ETH": ["04:15", "13:25"]},
            "tick_size": 0.05,
            "tick_value": 18.75,
            "point_value": 375,
        },
    },
    {
        "symbol": "CC",
        "name": "Cocoa Futures",
        "exchange": "ICEUS",
        "category": "agriculture",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro"],
        "data_start": "2008-01-02",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["04:45", "13:25"]},
            "tick_size": 1,
            "tick_value": 10,
            "point_value": 10,
        },
    },
    # --- Crypto ---
    {
        "symbol": "BTC",
        "name": "Bitcoin Futures",
        "exchange": "CME",
        "category": "crypto",
        "currency": "USD",
        "type": "futures",
        "default_session": "ETH",
        "events": ["macro", "crypto"],
        "data_start": "2018-01-17",
        "data_end": "2026-02-06",
        "notes": None,
        "config": {
            "sessions": {"ETH": ["18:00", "17:00"], "RTH": ["09:30", "16:00"]},
            "tick_size": 5,
            "tick_value": 25,
            "point_value": 5,
        },
    },
]


def main():
    sb = create_client(os.getenv("SUPABASE_URL"), os.getenv("SUPABASE_SERVICE_KEY"))

    # 1. Delete all existing
    existing = sb.table("instruments").select("symbol").execute()
    if existing.data:
        symbols = [r["symbol"] for r in existing.data]
        print(f"Deleting {len(symbols)} existing: {symbols}")
        for sym in symbols:
            sb.table("instruments").delete().eq("symbol", sym).execute()
        print("Deleted.\n")

    # 2. Insert all 31
    print(f"Inserting {len(INSTRUMENTS)} instruments...")
    for inst in INSTRUMENTS:
        inst["image_url"] = f"{STORAGE_BASE}/{inst['symbol']}.svg"
        inst["active"] = True
        sb.table("instruments").insert(inst).execute()
        notes_tag = " [notes]" if inst.get("notes") else ""
        print(f"  {inst['symbol']:>4} — {inst['name']}{notes_tag}")

    # 3. Verify
    result = sb.table("instruments").select("symbol").execute()
    print(f"\nDone. {len(result.data)} instruments in Supabase.")


if __name__ == "__main__":
    main()
